name: na_design
description: NA Danmark design system built on the Flutter widgets layer.
publish_to: none
version: 0.0.0

environment:
  sdk: ^3.11.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: 1.17.0
  na_kernel:
    path: ../na_kernel
  phosphor_flutter: 2.1.0

dev_dependencies:
  custom_lint: 0.8.1
  flutter_test:
    sdk: flutter
  na_lints:
    path: ../../../tool/na_lints
  na_testing:
    path: ../na_testing

flutter:
  uses-material-design: false
  fonts:
    - family: Plex
      fonts:
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
